### ISSUE TITLE
Cannot read property 'tap' of undefined on html-webpack-plugin 4.0.0-beta11

### ISSUE THREAD

**Issue by jasminexie** [dyw934854565/html-webpack-inject-attributes-plugin#3]
Hi, thank you for your hard work here! However, this plugin doesn't seem to be working with html-webpack-plugin 4.0.0-beta11. It appears they've altered their hooks api. I've played around with it and (disregarding backwards compatibility) the changes required to work with html-webpack-plugin 4.0.0-beta is minimal.

```javascript
// index.js
compiler.hooks.compilation.tap("htmlWebpackInjectAttributesPlugin", function (compilation) {
  HtmlWebpackPlugin
    .getHooks(compilation)
    .alterAssetTags.tap("htmlWebpackInjectAttributesPlugin", alterAssetTags.bind(self, compilation));
});
```

```javascript
// alterAssetTags.js
function alterAssetTags(compilation, htmlPluginData, callback) {
  // --- etc
  forEach(options, function(val, key) {
    addAttr(compilation, htmlPluginData.assetTags.scripts, key, val);
    addAttr(compilation, htmlPluginData.assetTags.styles, key, val);
  });
  // --- etc
}
```

I haven't made a PR yet because you might have other ideas about what features this library should include, since `data.assetTags` allow you to modify `script`, `link` and `meta` tags. Please give this some thought and if you'd like me to make a PR I'll be happy to contribute.

My team and I would appreciate it very much if you'd update this library to account for html-webpack-plugin 4.0.0-beta. Thanks again for creating and maintaining this plugin.

**Comment by dyw934854565** [comment]
done. use 1.0.3 instead
